import = [
  "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.94

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font Mono"

size = 12
